[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_gas_consumption_examples = "DBYZWu2VUr2LypbdN3dh6GKKGxRCi2cyEXGRjPByMTZf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shayan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
